# Generated by Django 5.0.6 on 2024-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pets',
            table='Pet',
        ),
        migrations.AlterModelTable(
            name='users',
            table='User',
        ),
    ]
